QALI-489: Replace the micrometer Meter registry by our own implementa…
qalipsis/qalipsis-plugin-influxdb pull request #21
Opened 2024-03-20 04:13 UTC by oceenachi

…tion

2024-04-05 12:12 UTC, ericjesse requested changes

2024-06-07 10:28 UTC, ericjesse requested changes

2024-06-07 10:35 UTC, ericjesse commented on influxdb/src/main/kotlin/io/qalipsis/plugins/influxdb/config/InfluxDbMeasurementPublisherFactory.kt
> +        private const val INFLUXDB_CONFIGURATION = "${MetersConfig.EXPORT_CONFIGURATION}.influxdb"
Move the constants to the config class.

2024-06-11 11:56 UTC, ericjesse requested changes

2024-06-11 11:56 UTC, ericjesse commented on influxdb/src/main/kotlin/io/qalipsis/plugins/influxdb/config/InfluxDbMeasurementPublisherFactory.kt
> + * @author Palina Bril
Change the author here.

2024-06-11 11:56 UTC, ericjesse commented on influxdb/src/main/kotlin/io/qalipsis/plugins/influxdb/config/InfluxDbMeasurementPublisherFactory.kt
> + * Configuration for the export of QALIPSIS meters to InfluxDb.
The documentation is not accurate.

2024-06-11 11:56 UTC, ericjesse commented on influxdb/src/main/kotlin/io/qalipsis/plugins/influxdb/meters/InfluxdbMeasurementPublisher.kt
> +            logger.trace { "onSuccess totally processed" }
Do you really need both traces?

2024-06-11 11:56 UTC, ericjesse commented on influxdb/src/main/kotlin/io/qalipsis/plugins/influxdb/meters/InfluxdbMeasurementPublisher.kt
> +        runBlocking(coroutineScope.coroutineContext) {
Why are you using a runblocking here? You are already in a suspended context.

2024-06-11 11:56 UTC, ericjesse commented on influxdb/src/main/kotlin/io/qalipsis/plugins/influxdb/meters/InfluxdbMeasurementPublisher.kt
> +    private fun String.replaceSpaces() = this.replace(" ", "-").lowercase()
The function does more than replacing spaces. `format` or `sanitize()` would probably be better.

2024-06-11 11:56 UTC, ericjesse commented on influxdb/src/main/resources/application-influxdb.yml
> +      prefix: influxdb
why not using `qalipsis` as prefix?

2024-06-11 11:56 UTC, ericjesse commented on influxdb/src/main/kotlin/io/qalipsis/plugins/influxdb/meters/InfluxdbMeasurementPublisher.kt
> +        return "${configuration.prefix}.${meterId.campaignKey.replaceSpaces()}.${meterId.scenarioName.replaceSpaces()}.${meterId.stepName.replaceSpaces()}.${meterId.meterName.replaceSpaces()},$tags $
What if the prefix is blank, will the name start with a dot?
I would rather calculate the complete prefix in the init {} block to determine whether it is a totally empty string or a real prefix with a dot.

2024-06-12 04:59 UTC, oceenachi commented on influxdb/src/main/resources/application-influxdb.yml
> +      prefix: influxdb
I thought the default prefix for the plugins should be the plugin name though.

2024-06-13 09:55 UTC, ericjesse commented on influxdb/src/main/resources/application-influxdb.yml
> +      prefix: influxdb
No, because other plugins will never store data in the influxdb.

2024-06-13 09:56 UTC, oceenachi commented on influxdb/src/main/resources/application-influxdb.yml
> +      prefix: influxdb
Noted

2024-06-14 06:33 UTC, ericjesse approved these changes

2024-06-14 06:33 UTC, ericjesse commented on influxdb/src/main/kotlin/io/qalipsis/plugins/influxdb/meters/InfluxdbMeasurementPublisher.kt
> +    private var prefix: String = if (configuration.prefix.isNotEmpty()) "${configuration.prefix}." else ""
why var? val should be enough

2024-06-14 06:33 UTC, ericjesse commented on influxdb/src/main/kotlin/io/qalipsis/plugins/influxdb/meters/InfluxdbMeasurementPublisher.kt
> +class InfluxdbMeasurementPublisher(
No need for the requires, the publisher is not a bean. It is created by the factory.

2024-06-14 06:33 UTC, ericjesse commented on influxdb/src/main/kotlin/io/qalipsis/plugins/influxdb/meters/InfluxDbMeasurementConfiguration.kt
> +@Requires(property = "$INFLUXDB_CONFIGURATION.enabled", value = "true")
```suggestion
@Requires(property = "$INFLUXDB_ENABLED", value = "StringUtils.TRUE")
```

2024-06-14 08:07 UTC, merged